# WATCH OUT!  This makefile is a work in progress.  It is probably missing
# tons of important things.  DO NOT RELY ON IT TO BUILD A GOOD LIBEVENT.

# Needed for correctness
# For optimization and warnings
!IF "$(DEBUG)"=="1" 
CXX_CFLAGS = $(CXX_CFLAGS) /W3 /wd4996 /nologo /MDd /Zi /EHsc -D_DEBUG -I.. /D__CXX_11__
LIBFLAGS=/nologo /INCREMENTAL /DEBUG /SUBSYSTEM:CONSOLE /DYNAMICBASE /NXCOMPAT
!ELSE 
CXX_CFLAGS = $(CXX_CFLAGS) /Ox /W3 /wd4996 /nologo /MD /EHsc -DNDEBUG -I.. /D__CXX_11__
LIBFLAGS=/nologo /INCREMENTAL /SUBSYSTEM:CONSOLE /DYNAMICBASE /NXCOMPAT
!ENDIF


# XXXX have a debug mode
   
TESTCAPI_TEST_OBJS = testcapi.obj

.cpp.obj::
    cl $(CXX_CFLAGS) -c $<
    
all: $(TESTCAPI_TEST_OBJS) 
	link $(LIBFLAGS) $(TESTCAPI_TEST_OBJS) ../xdelta.lib /out:../testcapi.exe /PDB:"testcapi.pdb" 

clean:
	del *.obj
	del ..\server.exe ..\client.exe ..\testcapi.exe ..\similarity.exe ..\testdiffcb.exe
	del *.manifest *.exp *.pdb
